services:
  - type: web
    name: erika-cordeiro-portfolio
    runtime: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    preDeployCommand: python manage.py migrate --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    autoDeployTrigger: commit
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_USE_SSL
        value: "False"
      - key: CONTACT_EMAIL
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
